### ISSUE TITLE
[Infra] Migrate from React to Next

### ISSUE THREAD

**Issue by sayakongit** [sayakongit/sangnet#166]
## Migrate from React to Next

**Description:**

The front end is made with React + Vite + Material UI. This is a great stack in my opinion. But the entire stuff was built during a hackathon so the code quality and structure is not even a bit standard. Most of the things are hacky in some ways. So it would be great help if the stack can be converted to NextJs (only Vanilla CSS and Tailwind can be used) keeping the look and feel of the current UI. Please everything with re-usable components and you may keep a better folder structure.

**Bonus 🥳**
The one who will complete the task, will receive a cool t-shirt from me personally.

**Comment by XronTrix10** [comment]
Assign me

**Comment by sayakongit** [comment]
Go ahead bro @XronTrix10

**Comment by sumit-kumar-jha1709** [comment]
@sayakongit if this issue is not resolved then kindly assign it to me under JWOC
