### ISSUE TITLE
[Frontend] Put a marker/dot on Map for User's location 

### ISSUE THREAD

**Issue by sayakongit** [sayakongit/sangnet#175]
## Put a marker/dot on Map for User's location 

**Description:**

Currently there is no marker for the user's current geo location. Add a marker similarly it is done for donors and blood banks.

**Comment by harith-hacky03** [comment]
I am ready to fix it . Can you assign me please?

**Comment by sayakongit** [comment]
Go ahead @harith-hacky03

**Comment by harith-hacky03** [comment]
I can't get into the home page itself its need auth but even if i signup it still give 400 for login

**Comment by sayakongit** [comment]
@harith-hacky03 Hey, please check if you have setup the backend and mind the env variables too.

**Comment by sayakongit** [comment]
@harith-hacky03 Updated the docs for setting up the env variables. Refer that and let me know if you face any problem.

**Comment by harith-hacky03** [comment]
@sayakongit  Sure

**Comment by harith-hacky03** [comment]
@sayakongit Can i add different icon for current user's location?

**Comment by harith-hacky03** [comment]
![sang](https://github.com/sayakongit/sangnet/assets/108193091/64fa8bad-9f6e-4329-a29b-1852a5639511)

If is it okay . I will make my PR and change env to back and pull it to you. Thank you.

**Comment by sayakongit** [comment]
Hey @harith-hacky03 don't worry, I need to fix the workflows. Thanks for the contribution! Let me review your PR and get back to you.

**Comment by harith-hacky03** [comment]
@sayakongit Sure if any changes let me know

**Comment by sayakongit** [comment]
@harith-hacky03 Could you please raise a issue for the bugs in workflows?
