### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by sayakongit** [sayakongit/sangnet#28]
### Description

We are using Material UI for as design library with ReactJS in the frontend. Dark mode support is not yet added yet in the project. A button for users to switch between light and dark mode is all we want. Should follow all the standards from MUI and do the necessary CSS changes to maintain the projects current design standards.

**Comment by Aaditya8C** [comment]
Can you assign it to me?

**Comment by sayakongit** [comment]
Sure @Aaditya8C you can work on this
