### ISSUE TITLE
Improve the front-end code quality

### ISSUE THREAD

**Issue by sayakongit** [sayakongit/sangnet#30]
The project being made in a hackathon, it includes a lot of hacky and not-recommended code in the front end side. Need to improve the code with utmost best practices keeping the UI/UX same.

**Comment by NeelGaji** [comment]
Can you assign this to me?

**Comment by sayakongit** [comment]
Hey @NeelGaji, sure! I am assigning this issue to you.

**Comment by weedertree** [comment]
@sayakongit could you please assign me with this issue, i'd love to improve the code quality :)
