### ISSUE TITLE
[Bug] Fix All Contributors Badge in README

### ISSUE THREAD

**Issue by sayakongit** [sayakongit/sangnet#85]
**Describe the bug**
The all-contributors badge is breaking in the Readme file. Follow the expected behavior mentioned below.

**To Reproduce**
1. Go to README.md file in the repo

**Expected behavior**
The All-contributors badge should show up in the center below the Banner image.

**Screenshots**
![image](https://github.com/sayakongit/sangnet/assets/83216382/fd0470b0-4b76-4eab-b704-0add5e78390a)

**Additional context**
NA

**Comment by anevski-stefan** [comment]
@sayakongit Can i work on this issue?

**Comment by sayakongit** [comment]
Sure @anevski-stefan

**Comment by anevski-stefan** [comment]
test
